In [2]:
import numpy as np

In [3]:
# Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
vector = np.arange(1, 11, dtype=int)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
# Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
m = np.random.randint(1, 11, size=(5, 5), dtype=int)
print(m)


[[ 9  9  9  5  2]
 [ 5  4  2  2 10]
 [ 8  2  1  6  2]
 [ 8  4  2  9  2]
 [ 3 10  9  3  1]]


In [6]:
# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
m = np.random.uniform(0, 1, size=(4, 4))
print(m)

[[0.99795767 0.44973823 0.87138809 0.31013278]
 [0.24122548 0.74972808 0.01191757 0.46252204]
 [0.7834242  0.8938165  0.85311065 0.43073776]
 [0.65329579 0.52950834 0.81932412 0.27187308]]


In [9]:
# Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте 
# на них поелементні операції додавання, віднімання та множення.
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print("array1:", array1)
print("array2:", array2)

sum_array = array1 + array2
print("Sum:", sum_array)

subtraction_array = array1 - array2
print("Subtraction:", subtraction_array)

multiplication_array = array1 * array2
print("Multiplication:", multiplication_array)

array1: [4 2 1 9 5]
array2: [1 8 3 1 1]
Sum: [ 5 10  4 10  6]
Subtraction: [ 3 -6 -2  8  4]
Multiplication: [ 4 16  3  9  5]


In [19]:
# Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
array1 = np.random.random(7)
array2 = np.random.random(7)
print("array1:\n", array1)

print("array2:\n", array2)

dot_array = np.dot(array1, array2)
print("Dot product:", dot_array)

array1:
 [0.78297022 0.09958531 0.8707163  0.5172985  0.7832003  0.61037505
 0.00434083]
array2:
 [0.48280707 0.75187438 0.53036855 0.61918004 0.11791035 0.02189541
 0.36131938]
Dot product: 1.3422809013718324


In [17]:
# Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print("matrix1:\n", matrix1)
print("matrix2:\n", matrix2)

dot_matrix = np.dot(matrix1, matrix2)
print("Dot matrix:\n", dot_matrix)

matrix1:
 [[ 2  3]
 [ 4 10]]
matrix2:
 [[10  2  4]
 [ 4  8  7]]
Dot matrix:
 [[32 28 29]
 [80 88 86]]


In [22]:
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 11, size=(3, 3))

print(matrix)

inverse_matrix = np.linalg.inv(matrix)
print("inverse_matrix: \n", inverse_matrix)


[[4 6 6]
 [3 4 1]
 [4 2 3]]
inverse_matrix: 
 [[-0.2   0.12  0.36]
 [ 0.1   0.24 -0.28]
 [ 0.2  -0.32  0.04]]


In [24]:
# Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix = np.random.rand(4, 4)
print(matrix)

transposed_matrix = matrix.T
print("Transposed Matrix:\n", transposed_matrix)


[[0.37957961 0.15804726 0.69216076 0.72573935]
 [0.50364343 0.33294189 0.63436831 0.95731232]
 [0.74348752 0.59453056 0.12962181 0.80367065]
 [0.13163997 0.05299006 0.70970546 0.32231424]]
Transposed Matrix:
 [[0.37957961 0.50364343 0.74348752 0.13163997]
 [0.15804726 0.33294189 0.59453056 0.05299006]
 [0.69216076 0.63436831 0.12962181 0.70970546]
 [0.72573935 0.95731232 0.80367065 0.32231424]]


In [26]:
# Створіть матрицю розміром 3x4 та вектор розміром 4,
# заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)

print("Matrix:\n", matrix)
print("Vector:\n", vector)

result = np.dot(matrix, vector)
print("Result:\n", result)

Matrix:
 [[1 7 5 5]
 [3 8 5 8]
 [9 2 3 5]]
Vector:
 [7 6 7 6]
Result:
 [114 152 126]


In [27]:
# Створіть матрицю розміром 2x3 та вектор розміром 3, 
# заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

print("Matrix:\n", matrix)
print("Vector:\n", vector)

result = np.dot(matrix, vector)
print("Result:\n", result)

Matrix:
 [[0.65751676 0.96648174 0.33575727]
 [0.74716679 0.4856553  0.47516585]]
Vector:
 [0.54945348 0.27180948 0.03327112]
Result:
 [0.63514479 0.5583484 ]


In [28]:
# Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("matrix1:\n", matrix1)
print("matrix2:\n", matrix2)

result = matrix1 * matrix2
print("Result:\n", result)

matrix1:
 [[1 6]
 [4 8]]
matrix2:
 [[1 9]
 [8 9]]
Result:
 [[ 1 54]
 [32 72]]


In [29]:
# Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("matrix1:\n", matrix1)
print("matrix2:\n", matrix2)

result = np.dot(matrix1, matrix2)
print("Result:\n", result)

matrix1:
 [[ 6  8]
 [ 7 10]]
matrix2:
 [[6 3]
 [3 8]]
Result:
 [[ 60  82]
 [ 72 101]]


In [32]:
# Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

matrix = np.random.randint(1, 101, size=(5, 5))
print("matrix:\n", matrix)

sum_matrix = np.sum(matrix)
print("Sum matrix:\n", sum_matrix)

matrix:
 [[ 86  55  26  12   2]
 [ 80 100  27  50  15]
 [ 11  23   3  33   5]
 [ 95  63  26  40  57]
 [ 66  41  27  29  53]]
Sum matrix:
 1025


In [33]:
# Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("matrix1:\n", matrix1)
print("matrix2:\n", matrix2)

result = matrix1 - matrix2
print("Result:\n", result)

matrix1:
 [[ 4  6  9  6]
 [ 2  1  2  7]
 [ 4  8 10  9]
 [ 2 10  9  6]]
matrix2:
 [[10  2  3  4]
 [ 1  8  4  3]
 [10  5  1  1]
 [ 6  5  6  7]]
Result:
 [[-6  4  6  2]
 [ 1 -7 -2  4]
 [-6  3  9  8]
 [-4  5  3 -1]]


In [40]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, 
# що містить суму елементів кожного рядка матриці.

matrix = np.random.rand(3, 3)
print("Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
column_vector = row_sums.reshape(-1, 1)

print("Column_vector:\n", column_vector)

Matrix:
 [[0.61332979 0.24637645 0.47307665]
 [0.25239289 0.85700827 0.53237547]
 [0.38838306 0.49178389 0.10289979]]
Column_vector:
 [[1.33278288]
 [1.64177662]
 [0.98306674]]


In [41]:
# Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix = np.random.randint(1, 11, size=(3, 4))
print("Matrix:\n", matrix)

squared_matrix = np.square(matrix)
print("Squared_matrix:\n", squared_matrix)

Matrix:
 [[ 2  4  5  8]
 [ 5  2 10  8]
 [ 8  4  7  5]]
Squared_matrix:
 [[  4  16  25  64]
 [ 25   4 100  64]
 [ 64  16  49  25]]


In [43]:
# Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 
# та знайдіть вектор з квадратними коренями цих чисел.
vector = np.random.randint(1, 51, size=4)
print("Vector:\n", vector)

sqrt_vector = np.sqrt(vector)
print("Sqrt_vector:\n", sqrt_vector)

Vector:
 [48 12 30 30]
Sqrt_vector:
 [6.92820323 3.46410162 5.47722558 5.47722558]
